data:
  #train: list of csv file
  train: ['./data/cbis-train.csv','./data/inbreast-train.csv']
  #val: list of csv file
  val: ['./data/cbis-val.csv','./data/inbreast-val.csv']
  #nc (number of classes): int
  nc: 2
  #names: list of classes names
  names: ['benign','malignant']

hyp:
  #pretrained: boolean
  pretrained: True
  #feature_extract: boolean
  feature_extract: False
  #batch_size: int
  batch_size: 16
  #total_epochs: int
  total_epochs: 100
  #lr (learning rate): float
  lr: 0.001
  #weight decay (L2 regularization): float
  weight_decay: 0.0001
  #momentum: float
  momentum: 0.9 
  